[tox]
env_list = py312, py313, py314, lint
isolated_build = true

[testenv]
description = Run tests with pytest
deps =
    pytest>=7.0
    faker==40.15.0
commands =
    pytest --doctest-modules --ignore=tmp {posargs:splatlog tests}
# Export an ENV var when testing so that code can conditionality execute on it,
# like
# 
#       if os.environ.get("TESTING"):
#           ...
# 
setenv =
    TESTING = 1

[testenv:lint]
description = Run linting and format check
deps =
    ruff>=0.15.0
commands =
    ruff check {posargs:splatlog tests}
    # TODO  Does not format exactly as IDE ruff plugin
    # ruff format --check {posargs:splatlog tests}

[testenv:fix]
description = Auto-fix linting and formatting issues
deps =
    ruff>=0.15.0
commands =
    ruff check --fix splatlog tests
    # TODO  Does not format exactly as IDE ruff plugin
    # ruff format splatlog tests