"""
Color utilities for generating distinguishable color palettes.

Provides tools for converting color values and creating palettes of colors
that can be deterministically assigned to strings (e.g., for syntax
highlighting or labeling).
"""

from colorsys import hsv_to_rgb
from zlib import crc32

import rich.repr

from splatlog.lib.text import fmt_seq


def as_hex_byte(n: float) -> str:
    """
    Convert a float in [0, 1] to a two-character hex string.

    Used for building hex RGB color strings like `#ff00aa`.

    ## Parameters

    -   `n`: A float between 0 and 1 (inclusive).

    ## Returns

    A two-character lowercase hex string representing the byte value.

    ## Examples

    ```python
    >>> as_hex_byte(0)
    '00'

    >>> as_hex_byte(1)
    'ff'

    >>> as_hex_byte(0.12345)
    '1f'

    >>> as_hex_byte(1.23)
    Traceback (most recent call last):
      ...
    ValueError: `n` must be between 0 and 1 (inclusive), given 1.23

    ```
    """
    if not (0 <= n <= 1):
        raise ValueError(
            f"`n` must be between 0 and 1 (inclusive), given {n!r}"
        )
    return format(round(n * 255), "02x")


class ColorPallet:
    """
    A palette of evenly-distributed colors in HSV space.

    Colors are generated by dividing the hue circle into equal segments while
    keeping saturation and value constant. This produces a set of visually
    distinct colors suitable for labeling or highlighting.

    The {py:meth}`modulo` method provides deterministic color assignment for
    strings using a hash function.
    """

    DEFAULT_SATURATION = 0.75
    """Default saturation for generated colors."""

    DEFAULT_VALUE = 0.75
    """Default value (brightness) for generated colors."""

    _size: int
    _saturation: float
    _value: float
    _hues: tuple[float, ...]
    _colors: tuple[str, ...]

    def __init__(
        self,
        size: int = 32,
        saturation: float = DEFAULT_SATURATION,
        value: float = DEFAULT_VALUE,
    ):
        """
        Create a new color palette.

        ## Parameters

        -   `size`: Number of colors in the palette.
        -   `saturation`: HSV saturation for all colors (0-1).
        -   `value`: HSV value (brightness) for all colors (0-1).
        """
        self._size = size
        self._saturation = saturation
        self._value = value
        self._hues = tuple((float(i) / size) for i in range(size))
        self._colors = tuple(self.rgb_hex_for(hue) for hue in self._hues)

    @property
    def size(self) -> int:
        """The number of colors in the palette."""
        return self._size

    @property
    def saturation(self) -> float:
        """The HSV saturation for all colors in the palette."""
        return self._saturation

    @property
    def value(self) -> float:
        """The HSV value (brightness) for all colors in the palette."""
        return self._value

    @property
    def hues(self) -> tuple[float, ...]:
        """The hue values for each color in the palette."""
        return self._hues

    @property
    def colors(self) -> tuple[str, ...]:
        """The hex RGB color strings for each color in the palette."""
        return self._colors

    def __repr__(self) -> str:
        return (
            f"<{self.__class__.__name__} "
            f"hsl=(i/{self._size!r}, {self._saturation!r}, {self._value!r}) "
            f"colors={fmt_seq(self._colors, items=3)}>"
        )

    def __rich_repr__(self) -> rich.repr.Result:
        yield "size", self._size
        yield "saturation", self._saturation
        yield "value", self._value
        yield "colors", self._colors

    def rgb_hex_for(self, hue: float) -> str:
        """
        Convert an HSV hue to a hex RGB color string.

        Uses the palette's saturation and value settings.

        ## Parameters

        -   `hue`: The hue value (0-1).

        ## Returns

        A hex RGB color string like `#bf5f5f`.
        """
        return "#{:02x}{:02x}{:02x}".format(
            *(
                round(n * 255)
                for n in hsv_to_rgb(hue, self._saturation, self._value)
            )
        )

    def modulo(self, label: str) -> str:
        """
        Get a deterministic color for a string label.

        Uses CRC32 hashing to map the label to a palette index, ensuring the
        same label always gets the same color.

        ## Parameters

        -   `label`: The string to assign a color to.

        ## Returns

        A hex RGB color string from the palette.
        """
        return self._colors[crc32(bytes(label, encoding="utf-8")) % self._size]
